repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.87.1
    hooks:
      - id: terraform_docs
        args: [--args=--hide providers]
      - id: terraform_fmt
      - id: terraform_tflint
        args: [--args=--config=.tflint.hcl]
      - id: terraform_tfsec
      - id: terraform_validate
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-aws-credentials
      - id: mixed-line-ending
      - id: trailing-whitespace